### ISSUE TITLE
New xcel files for Tripoli

### ISSUE THREAD

**Issue by larseau** [CIRDLES/Tripoli-Issues#1]
After an update of the Mat262, it now delivers XLSB data files. These are presently not readable in Tripoli. The ratios that Tripoli should import are the "raw ratios" from the "ratio calculation" sheet as you can see from the attached XLSB files (As I could not upload XLSB files here I uploaded them as XLSX files here, but I don't think that should make a difference. I attach two different files, the only difference being which and how many ratios that has been collected).

I will be most grateful if you could help me on this issue. Thanks in advance.

Best regards,
Lars 

[NBSS6.xlsx](https://github.com/CIRDLES/Tripoli-Issues/files/773803/NBSS6.xlsx)
[NBSS6_1.xlsx](https://github.com/CIRDLES/Tripoli-Issues/files/773804/NBSS6_1.xlsx)

**Comment by bowring** [comment]
I will have a look at this soon.

**Comment by bowring** [comment]
These files are Excel binaries, so I saved them as xls files to examine.  The tabs and contents are very different from the normal xls files that Tripoli reads.  Adapting to this file format will take a considerable investment in time.  I am currently solo on Tripoli and committed in the short term to other research grants.  If you can raise a US$25000 grant, I could handle this over the summer 2017.  However, @noahmclean, myself, and others are considering putting together a 3-year grant to extend and modernize Tripoli to accommodate the advances we have made while learning to process LAICPMS data.  In that scenario, we will not read the excel files alone, but have access to the raw counts and voltages as well.

**Comment by larseau** [comment]
Thank you for taking a look at this. We unfortunately do not have those money. But I found a solution creating a new xcel sheet in the same format as isotopx xls files that Tripoli reads.

**Comment by larseau** [comment]
Dear Jim,

I've now got a student that is interested in updating tripoli to read our
strange MAT262 mass spectrometer output files. In that regard I was
wondering if we could get access to the tripoli code?

Best regards,

Lars Augland

**Comment by bowring** [comment]
I replied privately
