### ISSUE TITLE
GSC Raw Triton files - getting into Tripoli

### ISSUE THREAD

**Issue by NicoleRayner** [CIRDLES/Tripoli-Issues#2]
Below is a screen snap of a raw Triton file here at the GSC.  The second row of text has a value associated with it. The date is given as Year-Month-Day.  There is an underscore in the Sample ID, and the Comment section has some text, and the 
![headers of raw triton file](https://user-images.githubusercontent.com/40035242/46971072-f9cea800-d088-11e8-8853-84c1f6b91ea0.JPG)
In order to get this raw data into Tripoli we use a little custom utility that converts a few things:
The second row of text appears to be just text. Day/Month/Year (including backslashes) for the dates. no underscore in the Sample ID, a number 10 in the comments (I understand that this just puts a "line" every 10 rows or something)

![headers of triton for tripoli file](https://user-images.githubusercontent.com/40035242/46971151-300c2780-d089-11e8-9b52-672afe537919.JPG)

Any thoughts of how we might be able to avoid have to use this intermediate utility (one less step) would be great.  Thanks,
Here is a raw Pb file if you want to try with it from scratch.
[1562_01_1_Pb_F.zip](https://github.com/CIRDLES/Tripoli-Issues/files/2480092/1562_01_1_Pb_F.zip)

**Comment by bowring** [comment]
@NicoleRayner - finally getting to this ... note that project is now here: https://github.com/bowring/Tripoli

Can you supply the utility you use?  Note - the "10" is the cycles per block (denoted by lines on the graphs).

**Comment by NicoleRayner** [comment]
I'm going to pass this over to the scientist in charge of the TIMS lab for follow up.

**Comment by bowring** [comment]
determined to be non-issue in April 2021
