### ISSUE TITLE
download of latest release

### ISSUE THREAD

**Issue by ryanickert** [CIRDLES/Tripoli-Issues#3]
Hi Jim,  I can't find a place to download the latest Tripoli from other than a blind link you sent me back in 2015 that directs to v4.8.  Is there an easier way to get this?  Thanks!

**Comment by bowring** [comment]
go [here](http://cirdles.org/projects/tripoli/).  Let me know if you have issues.

**Comment by ryanickert** [comment]
Ahhh, thanks Jim.  Somehow the link on the website didn't show up on my colleagues computer, which is where I was looking for it (the computer is in a bit of a state, so the problem is definitely on our end).
